apiVersion: v1
kind: Service
metadata:
  name: example-service-nodeport
spec:
  ports:
  - name: web-port
    port: 80
    targetPort: 80
    nodePort: 32222
  selector:
    app: example-pod-label
  type: NodePort
